name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Setup golang 1.15.11 for all platforms except darwin
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.11'
      - name: Build for all platforms except darwin
        run: ${GITHUB_WORKSPACE}/build.sh -s whichca ${{ steps.get_version.outputs.VERSION }} darwin/arm64 darwin/amd64
      - name: Setup golang 1.16.3 for darwin
        uses: actions/setup-go@v2
        with:
          go-version: '1.6.4'
      - name: Build for darwin
        run: ${GITHUB_WORKSPACE}/build.sh whichca ${{ steps.get_version.outputs.VERSION }} darwin/arm64 darwin/amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: whichca_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
