name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Setup golang 1.20
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build for all platforms
        run: ${GITHUB_WORKSPACE}/build.sh whichca ${{ steps.get_version.outputs.VERSION }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: whichca_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

